export const STARTER_INVENTORY_ITEMS = [
  {
    name: 'Field Service Kit',
    sku: 'KIT-204',
    description: 'Pre-packed installation kit with connectors, labels, and handheld service essentials.',
    category: 'Field gear',
    quantity: 18,
    unitPrice: 149,
    reorderLevel: 8,
    location: 'Berlin warehouse A1',
    supplier: 'Northern Tools GmbH',
    tags: 'field, scheduled, restock-q2',
    orderedOn: '2026-04-08',
    expectedOn: '2026-04-19',
    receivedOn: null,
  },
  {
    name: 'Packaging Tape 48mm',
    sku: 'PKG-019',
    description: 'Heavy-duty packing tape for outbound fulfillment and replacement packaging.',
    category: 'Packing',
    quantity: 6,
    unitPrice: 12,
    reorderLevel: 10,
    location: 'Packing station B2',
    supplier: 'WrapFlow Supply',
    tags: 'shipping, low-stock, consumable',
    orderedOn: '2026-04-06',
    expectedOn: '2026-04-12',
    receivedOn: '2026-04-11',
  },
  {
    name: 'Barcode Scanner Dock',
    sku: 'SCAN-112',
    description: 'Charging dock used by floor staff for barcode scanners and cycle-count workflows.',
    category: 'Hardware',
    quantity: 0,
    unitPrice: 89,
    reorderLevel: 3,
    location: 'Ops shelf C4',
    supplier: 'ScanGrid Systems',
    tags: 'hardware, out-of-stock, accessories',
    orderedOn: '2026-04-15',
    expectedOn: '2026-04-24',
    receivedOn: null,
  },
];
