export const STARTER_INVENTORY_ITEMS = [
  {
    name: 'Field Service Kit',
    sku: 'KIT-204',
    description: 'Pre-packed installation kit with connectors, labels, and handheld service essentials.',
    category: 'Field gear',
    quantity: 18,
    unitPrice: 149,
    reorderLevel: 8,
    location: 'Berlin warehouse A1',
    supplier: 'Northern Tools GmbH',
    tags: 'premium, field, restock-q2',
  },
  {
    name: 'Packaging Tape 48mm',
    sku: 'PKG-019',
    description: 'Heavy-duty packing tape for outbound fulfillment and replacement packaging.',
    category: 'Packing',
    quantity: 6,
    unitPrice: 12,
    reorderLevel: 10,
    location: 'Packing station B2',
    supplier: 'WrapFlow Supply',
    tags: 'shipping, low-stock, consumable',
  },
  {
    name: 'Barcode Scanner Dock',
    sku: 'SCAN-112',
    description: 'Charging dock used by floor staff for barcode scanners and cycle-count workflows.',
    category: 'Hardware',
    quantity: 0,
    unitPrice: 89,
    reorderLevel: 3,
    location: 'Ops shelf C4',
    supplier: 'ScanGrid Systems',
    tags: 'hardware, out-of-stock, accessories',
  },
];

