export const STARTER_SUPPLIERS = [
  {
    name: 'Northern Tools GmbH',
    contactName: 'Leonie Hartmann',
    email: 'orders@northerntools.example',
    phone: '+49 30 5550 1201',
    leadTimeDays: 8,
    address: 'Alexanderplatz 14, Berlin, Germany',
    notes: 'Primary partner for field gear and technician kits.',
  },
  {
    name: 'WrapFlow Supply',
    contactName: 'Marta Sloan',
    email: 'ops@wrapflow.example',
    phone: '+44 20 8042 4410',
    leadTimeDays: 4,
    address: 'Docklands Trade Park, London, United Kingdom',
    notes: 'Fast-moving packing materials with short replenishment cycles.',
  },
  {
    name: 'ScanGrid Systems',
    contactName: 'Jonas Richter',
    email: 'service@scangrid.example',
    phone: '+49 89 4418 2230',
    leadTimeDays: 12,
    address: 'Technikring 7, Munich, Germany',
    notes: 'Barcode and warehouse scanning equipment vendor.',
  },
  {
    name: 'Aster Industrial Parts',
    contactName: 'Nina Bader',
    email: 'purchasing@asterparts.example',
    phone: '+49 211 6009 7120',
    leadTimeDays: 14,
    address: 'Industriestrasse 61, Dusseldorf, Germany',
    notes: 'Backup supplier for maintenance and replacement hardware.',
  },
  {
    name: 'Lumina Safety Group',
    contactName: 'Marco De Luca',
    email: 'warehouse@luminasafety.example',
    phone: '+39 02 8843 9900',
    leadTimeDays: 6,
    address: 'Via Torino 28, Milan, Italy',
    notes: 'Safety signage, PPE bundles, and compliance consumables.',
  },
  {
    name: 'BluePort Components',
    contactName: 'Eva Novak',
    email: 'sales@blueport.example',
    phone: '+420 221 440 987',
    leadTimeDays: 10,
    address: 'Pristavni 10, Prague, Czech Republic',
    notes: 'Accessory components and short-run electronics.',
  },
];

export const STARTER_INVENTORY_ITEMS = [
  {
    name: 'Field Service Kit',
    sku: 'KIT-204',
    description: 'Pre-packed installation kit with connectors, labels, and handheld service essentials.',
    category: 'Field gear',
    quantity: 18,
    unitPrice: 149,
    reorderLevel: 8,
    location: 'Berlin warehouse A1',
    supplier: 'Northern Tools GmbH',
    purchaseOrderNumber: 'PO-2048',
    quantityOnOrder: 12,
    orderStatus: 'ordered',
    tags: 'field, scheduled, restock-q2',
    orderedOn: '2026-04-08',
    expectedOn: '2026-04-19',
    receivedOn: null,
  },
  {
    name: 'Packaging Tape 48mm',
    sku: 'PKG-019',
    description: 'Heavy-duty packing tape for outbound fulfillment and replacement packaging.',
    category: 'Packing',
    quantity: 6,
    unitPrice: 12,
    reorderLevel: 10,
    location: 'Packing station B2',
    supplier: 'WrapFlow Supply',
    purchaseOrderNumber: 'PO-2081',
    quantityOnOrder: 4,
    orderStatus: 'partial',
    tags: 'shipping, low-stock, consumable',
    orderedOn: '2026-04-06',
    expectedOn: '2026-04-12',
    receivedOn: '2026-04-11',
  },
  {
    name: 'Barcode Scanner Dock',
    sku: 'SCAN-112',
    description: 'Charging dock used by floor staff for barcode scanners and cycle-count workflows.',
    category: 'Hardware',
    quantity: 0,
    unitPrice: 89,
    reorderLevel: 3,
    location: 'Ops shelf C4',
    supplier: 'ScanGrid Systems',
    purchaseOrderNumber: 'PO-2119',
    quantityOnOrder: 6,
    orderStatus: 'ordered',
    tags: 'hardware, overdue, accessories',
    orderedOn: '2026-04-02',
    expectedOn: '2026-04-10',
    receivedOn: null,
  },
  {
    name: 'Hydraulic Lift Sensor',
    sku: 'LIFT-044',
    description: 'Replacement sensor used during scheduled maintenance for loading lifts.',
    category: 'Maintenance',
    quantity: 5,
    unitPrice: 234,
    reorderLevel: 4,
    location: 'Maintenance cage D1',
    supplier: 'Aster Industrial Parts',
    purchaseOrderNumber: 'PO-1988',
    quantityOnOrder: 0,
    orderStatus: 'received',
    tags: 'maintenance, calibrated, receiving-complete',
    orderedOn: '2026-03-22',
    expectedOn: '2026-04-02',
    receivedOn: '2026-04-03',
  },
  {
    name: 'Safety Vest Bundle',
    sku: 'SAFE-330',
    description: 'Hi-vis safety vest set used for new team member onboarding and visitor kits.',
    category: 'Safety',
    quantity: 42,
    unitPrice: 29,
    reorderLevel: 12,
    location: 'Safety aisle E2',
    supplier: 'Lumina Safety Group',
    purchaseOrderNumber: null,
    quantityOnOrder: 0,
    orderStatus: 'none',
    tags: 'ppe, onboarding, compliant',
    orderedOn: null,
    expectedOn: null,
    receivedOn: null,
  },
  {
    name: 'Network Relay Module',
    sku: 'NET-880',
    description: 'Control relay used in retrofit kits for warehouse network cabinets.',
    category: 'Electronics',
    quantity: 9,
    unitPrice: 176,
    reorderLevel: 5,
    location: 'Secure cabinet F1',
    supplier: 'BluePort Components',
    purchaseOrderNumber: 'PO-2147',
    quantityOnOrder: 0,
    orderStatus: 'cancelled',
    tags: 'cancelled-order, retrofit, electrical',
    orderedOn: '2026-04-01',
    expectedOn: '2026-04-15',
    receivedOn: null,
  },
  {
    name: 'Label Cartridge XL',
    sku: 'LAB-611',
    description: 'Extended-use cartridge for industrial label printers in receiving and dispatch.',
    category: 'Consumables',
    quantity: 2,
    unitPrice: 41,
    reorderLevel: 9,
    location: 'Receiving bay R2',
    supplier: 'WrapFlow Supply',
    purchaseOrderNumber: null,
    quantityOnOrder: 0,
    orderStatus: 'none',
    tags: 'consumable, low-stock, printing',
    orderedOn: null,
    expectedOn: null,
    receivedOn: null,
  },
  {
    name: 'Docking Station Cable Pack',
    sku: 'CAB-205',
    description: 'Cable pack for workstation docking stations deployed in operational admin desks.',
    category: 'Accessories',
    quantity: 25,
    unitPrice: 22,
    reorderLevel: 10,
    location: 'Admin supply room G3',
    supplier: 'Northern Tools GmbH',
    purchaseOrderNumber: 'PO-2160',
    quantityOnOrder: 5,
    orderStatus: 'ordered',
    tags: 'accessory, upcoming, deskside',
    orderedOn: '2026-04-14',
    expectedOn: '2026-04-22',
    receivedOn: null,
  },
];

export const STARTER_ACTIVITY_LOG = [
  {
    sku: 'KIT-204',
    type: 'create',
    quantityDelta: 18,
    previousQuantity: 0,
    nextQuantity: 18,
    purchaseOrderNumber: 'PO-2048',
    note: 'Created the April field service replenishment line.',
    effectiveOn: '2026-04-08',
    createdAt: '2026-04-08T08:15:00Z',
  },
  {
    sku: 'KIT-204',
    type: 'update',
    quantityDelta: 2,
    previousQuantity: 16,
    nextQuantity: 18,
    purchaseOrderNumber: 'PO-2048',
    note: 'Adjusted kit count after final QA review.',
    effectiveOn: '2026-04-09',
    createdAt: '2026-04-09T10:00:00Z',
  },
  {
    sku: 'PKG-019',
    type: 'receive',
    quantityDelta: 4,
    previousQuantity: 2,
    nextQuantity: 6,
    purchaseOrderNumber: 'PO-2081',
    note: 'Partial tape delivery received at packing station.',
    effectiveOn: '2026-04-11',
    createdAt: '2026-04-11T09:20:00Z',
  },
  {
    sku: 'PKG-019',
    type: 'issue',
    quantityDelta: -3,
    previousQuantity: 9,
    nextQuantity: 6,
    purchaseOrderNumber: 'PO-2081',
    note: 'Issued tape rolls to outbound fulfillment.',
    effectiveOn: '2026-04-14',
    createdAt: '2026-04-14T15:05:00Z',
  },
  {
    sku: 'LIFT-044',
    type: 'adjust',
    quantityDelta: -1,
    previousQuantity: 6,
    nextQuantity: 5,
    purchaseOrderNumber: 'PO-1988',
    note: 'Cycle count corrected one sensor variance.',
    effectiveOn: '2026-04-13',
    createdAt: '2026-04-13T11:40:00Z',
  },
  {
    sku: 'SAFE-330',
    type: 'csv_import',
    quantityDelta: 42,
    previousQuantity: 0,
    nextQuantity: 42,
    purchaseOrderNumber: null,
    note: 'Imported onboarding safety stock from migration spreadsheet.',
    effectiveOn: '2026-04-05',
    createdAt: '2026-04-05T07:50:00Z',
  },
  {
    sku: 'LAB-611',
    type: 'seed',
    quantityDelta: 2,
    previousQuantity: 0,
    nextQuantity: 2,
    purchaseOrderNumber: null,
    note: 'Loaded low-stock printing consumables into demo workspace.',
    effectiveOn: '2026-04-16',
    createdAt: '2026-04-16T08:35:00Z',
  },
  {
    sku: 'LEG-900',
    inventoryItemName: 'Legacy Label Cartridge',
    type: 'delete',
    quantityDelta: -4,
    previousQuantity: 4,
    nextQuantity: 0,
    purchaseOrderNumber: null,
    note: 'Removed discontinued legacy cartridge after product sunset.',
    effectiveOn: '2026-04-07',
    createdAt: '2026-04-07T16:30:00Z',
  },
];
